function getConstants() { //TODO: Set proper ranges based on real data
  return {
    TEACHER_EMAIL_CELL: "B2",
    DATA_START_ROW: 3,
    DATA_START_COLUMN: 1,
    SLOT_COLUMN: 0,
    FIRST_STUDENT_COLUMN: 2,
    SCRIPT_PROPERTY_KEY: 'previousBookings',
    COURSE_RANGE_IN_TEACHER_TAB:"B3:B",
    STUDENT_STATUS:"Withdrawn",
    STUDENT_TAB_NAME:"Student",
    TEACHER_EMAIL_AND_ID_REANGE:"D2:E20",
    TEACHER_ID_RANGE_STRING:"E2:E", 
    META_TAB_NAME:"Meta",
    HOURS_CELL_REFRENCE_IN_META_SHEET:"L2:M12",
    EXPORT_ID:'1jfAdP08QXm7vQ8ju5zqOyqbShI1yRIAa',
    WITHDRAWN_TAB_NAME:"Withdrawn Students",
    INDIVIDUAL_CELL:"M",
    COURSE_COLUMN_RANGE:"K4:K",
    GET_TEACHER_TEMPLATE_TAB_NAME:"Teacher Template",
    TEACHER_MASTER_TAB_NAME:"Teacher Master",
    TEACHER_DETAILS_RANGE: "A2:K2",
    SLOT_RANGE_IN_META_TAB:"P2:S2",
    HOUR_START_COL_NUMBER:13,
    HOUR_END_COL_NUMBER:16,
    STUDENT_NAME_COL:"I"
  };
}