function getConstants() {
  return {
    TEACHER_EMAIL_CELL: "B2",
    DATA_START_ROW: 3,
    DATA_START_COLUMN: 1,
    SLOT_COLUMN: 0,
    FIRST_STUDENT_COLUMN: 2,
    SCRIPT_PROPERTY_KEY: 'previousBookings',
    COURSE_RANGE_IN_TEACHER_TAB:"B3:B",
    STUDENT_STATUS:"Withdrawn",
    STUDENT_TAB_NAME:"Student",
    TEACHER_EMAIL_AND_ID_REANGE:"D2:E20",
    TEACHER_ID_RANGE_STRING:"E2:E4",
    META_TAB_NAME:"Meta",
    HOURS_CELL_REFRENCE_IN_META_SHEET:"L2:M12"

  };
}